import { resolveApiBaseUrl } from "./apiBaseUrl";

export const APP_NAME = "CTSE Microservice System";

export const API_BASE_URL = resolveApiBaseUrl();

export const ROLES = {
    ADMIN: "ADMIN",
    USER: "USER",
    DELIVERY: "DELIVERY",
};

export const ORDER_STATUS = {
    PENDING: "PENDING",
    ASSIGNED: "ASSIGNED",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    COMPLETED: "COMPLETED",
    CANCELLED_BY_USER: "CANCELLED_BY_USER",
    CANCELLED_BY_ADMIN: "CANCELLED_BY_ADMIN",
    CANCELLED_BY_DELIVERY: "CANCELLED_BY_DELIVERY",
};

export const ORDER_STATUS_FLOW = [
    "PENDING",
    "ASSIGNED",
    "OUT_FOR_DELIVERY",
    "COMPLETED",
    "CANCELLED_BY_USER",
    "CANCELLED_BY_ADMIN",
    "CANCELLED_BY_DELIVERY",
];

export const ORDER_STATUS_OPTIONS = [
    "PENDING",
    "ASSIGNED",
    "OUT_FOR_DELIVERY",
    "COMPLETED",
    "CANCELLED_BY_USER",
    "CANCELLED_BY_ADMIN",
    "CANCELLED_BY_DELIVERY",
];

export const PRODUCT_STATUS = {
    AVAILABLE: "AVAILABLE",
    RESERVED: "RESERVED",
};

export const DELIVERY_STATUS_OPTIONS = [
    "PICKED_UP",
    "OUT_FOR_DELIVERY",
    "COMPLETED",
    "CANCELLED_BY_DELIVERY",
];

export const DELIVERY_PRIORITY_OPTIONS = ["NORMAL", "HIGH", "URGENT"];

export const DELIVERY_ALLOWED_STATUS_FOR_DELIVERY_ROLE = [
    "COMPLETED",
    "CANCELLED_BY_DELIVERY",
];
